routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');*/

Route::get('/dashboard', function(){
    return redirect('/');  
})->middleware(['auth', 'verified'])->name('dashboard');
Route::get('/', function(){
    $user = Auth::user();
    if($user->isDeleted()){
        return redirect('/app/deregistered');
    }
    if ($user->account_type == 'Admin') {
        return redirect('/app/admin');
    }
    if (in_array($user->account_type, ['Customer', 'Vendor'])) {
        return redirect('/mine');
    }   
})->middleware(['auth', 'verified', 'require-registration'])->name('dashboard');

Route::get('/app/test', 'App\Http\Controllers\AppController@test')->middleware(['auth', 'verified'])->name('app.test');
Route::match(['GET', 'POST'], '/complete-registration/{token}', 'App\Http\Controllers\AppController@completeRegistration')->name('app.complete-registration');

Route::get('/app/admin', 'App\Http\Controllers\AppController@admin')->middleware(['auth', 'verified'])->name('app.admin');
Route::get('/app/showcustomer', 'App\Http\Controllers\AppController@showCustomer')->middleware(['auth', 'verified'])->name('app.showCustomer');
Route::get('/app/addaccount', 'App\Http\Controllers\AppController@addAccount')->middleware(['auth', 'verified'])->name('app.addaccount');
Route::get('/app/user/{userId}', 'App\Http\Controllers\AppController@user')->middleware(['auth', 'verified'])->name('app.user');
Route::get('/app/edituser/{userId}', 'App\Http\Controllers\AppController@editUser')->middleware(['auth', 'verified'])->name('app.edituser');
Route::get('/app/search-hcp', 'App\Http\Controllers\AppController@searchHcp')->middleware(['auth', 'verified'])->name('app.search-hcp');
Route::post('/app/store-account', 'App\Http\Controllers\AppController@storeAccount')->middleware(['auth', 'verified'])->name('app.store-account');
Route::get('/app/sendmail', 'App\Http\Controllers\AppController@mailNewAccountNotification')->middleware(['auth', 'verified'])->name('app.sendmail');
Route::post('/app/add-note', 'App\Http\Controllers\AppController@addNote')->middleware(['auth', 'verified'])->name('app.add-note');
Route::get('/app/delete-historical-note/{id}', 'App\Http\Controllers\AppController@deleteHistoricalNote')->middleware(['auth', 'verified'])->name('app.deleteHistoricalNote');
Route::post('/app/update-account/{id}', 'App\Http\Controllers\AppController@updateAccount')->middleware(['auth', 'verified'])->name('app.update-account');
Route::get('/app/toggle-user-activation/{id}', 'App\Http\Controllers\AppController@toggleUserActivation')->middleware(['auth', 'verified'])->name('app.toggleUserActivation');

Route::get('/search', 'App\Http\Controllers\AppController@search')->middleware(['auth', 'verified'])->name('app.search');

Route::get('/mine', 'App\Http\Controllers\MineController@index')->middleware(['auth', 'verified'])->name('mine.index');
Route::get('/mine/work-orders', 'App\Http\Controllers\MineController@workOrders')->middleware(['auth', 'verified'])->name('mine.workOrders');
Route::get('/mine/view-work-order/{workOrderId}', 'App\Http\Controllers\MineController@viewWorkOrder')->middleware(['auth', 'verified'])->name('mine.viewWorkOrder');
Route::get('/mine/view-work-order-details/{workOrderId}', 'App\Http\Controllers\MineController@viewWorkOrderDetails')->middleware(['auth', 'verified'])->name('mine.viewWorkOrderDetails');
Route::get('/mine/view-work-order-line-items/{workOrderId}', 'App\Http\Controllers\MineController@viewWorkOrderLineItems')->middleware(['auth', 'verified'])->name('mine.viewWorkOrderLineItems');
Route::get('/mine/view-work-order-pdf/{workOrderId}', 'App\Http\Controllers\MineController@viewWorkOrderPdf')->middleware(['auth', 'verified'])->name('mine.viewWorkOrderPdf');
Route::match(['GET','POST'], '/mine/add-request', 'App\Http\Controllers\MineController@addRequest')->middleware(['auth', 'verified'])->name('mine.addRequest');
Route::get('/mine/work-order-ticket-selection', 'App\Http\Controllers\MineController@workOrderTicketSelection')->middleware(['auth', 'verified'])->name('mine.workOrderTicketSelection');

Route::get('/tickets', 'App\Http\Controllers\TicketsController@index')->middleware(['auth', 'verified'])->name('tickets');
Route::get('/tickets/view/{id}', 'App\Http\Controllers\TicketsController@view')->middleware(['auth', 'verified'])->name('tickets.view');
Route::post('/tickets/add-note/{id}', 'App\Http\Controllers\TicketsController@addNote')->middleware(['auth', 'verified'])->name('tickets.addNote');
Route::get('/tickets/delete-historical-note/{id}', 'App\Http\Controllers\TicketsController@deleteHistoricalNote')->middleware(['auth', 'verified'])->name('tickets.deleteHistoricalNote');
Route::post('/tickets/set-status/{id}', 'App\Http\Controllers\TicketsController@setStatus')->middleware(['auth', 'verified'])->name('tickets.setStatus');
Route::get('/tickets/get-work-order-name/{id}', 'App\Http\Controllers\TicketsController@getWorkOrderName')->middleware(['auth', 'verified'])->name('tickets.getWorkOrderName');


require __DIR__.'/auth.php';

app/View/Components/Forminput.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Forminput extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($params)
    {
        $this->params = $params;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        $defaults = [
            'placeholder' => '' ,
            'type' => 'text', 
            'value' => '',
        ];
        foreach($defaults as $key => $value) {
            if(!isset($this->params[$key])) {
                $this->params[$key] = $value;
            }
        }

        return view('components.forms.input', [
            'params' => $this->params, 
        ]);
    }
}

resources/views/app/addOrEditAccount.blade.php
@extends('layouts.app', ['header' => 'New Portal Account'])

@section('content')

    @if(!$isEdit)

        {{ Form::open(['url' => '/app/store-account']) }}
    
    @else 

        {{ Form::model($user, ['url' => '/app/update-account/'.$user->id]) }}

    @endif 

    <h3 class="text-yellow-600">Account Info</h3>
    <div class="w-full lg:w-2/6 inline-block">
        <x-forminput :params="['type' => 'select', 'name' => 'account_type', 'value' => $user->account_type ?? '', 'label' => 'Type', 'options' => ['' => '' , 'Customer' => 'Customer']]" />
        
    </div>
    <div class="clearfix"></div>

    <div class="w-full lg:w-2/6 inline-block">
        <x-forminput :params="['type' => 'text', 'name' => 'name', 'label' => 'Name', 'value' => $user->name ?? '']" />
        
    </div>
    <div class="w-full lg:w-2/6 inline-block">
        <x-forminput :params="['type' => 'text', 'name' => 'email', 'label' => 'Email', 'value' => $user->email ?? '']" />
    </div>

    @if(!$isEdit)

    <div class="w-full lg:w-2/6 inline-block">
        <!-- Random Password: <strong>{{ $randomPassword }}</strong> -->
        <x-forminput :params="['type' => 'password', 'name' => 'pass', 'label' => 'Password', 'disabled' => 'disabled', 'value' => $randomPassword]" />
        <span class="text-xs text-gray-600">Random Password: <strong>{{ $randomPassword }}</strong></span>
        <input type="hidden" name="pass" value="{{ $randomPassword }}">
    </div>

    @endif 

    @if(!empty($user))

    <div class="my-4">
        <label>
            <input type="checkbox" name="change_account" value="1" id="AccountChangeIndicator" />
            <span class="ml-2">Update HCP Account</span>
        </label>
    </div>
    @endif
    
    <hr class="my-5">
    
    <div id="HcpAccountLinkContainer">
        <div class="w-full lg:w-4/6 inline-block relative border-b border-gray-300">
            <h3 class="text-yellow-600">Locate in HCP</h3>
            <span class="absolute top-8 left-0">
                <button x-on="SearchHcp" id="HcpSearchSubmit"><x-icon type="search" fill="1" /></button>
            </span>
            <input type="text" id="HcpSearch" class="ml-8 w-full border-0 focus:border-0" placeholder="HCP Search">
        </div>

        <div class="w-full" id="HcpSearchResultsContainer">
            ...
        </div>
    </div>

    <input type="hidden" name="external_name" id="ExternalName" value="{{ $user->external_name ?? '' }}">
    <x-submitbutton />
    {{ Form::close() }} 

    <script>
        
        $(document).ready(function() {

            $('#AccountChangeIndicator').click(function(){
                if(this.checked){
                    $('#HcpAccountLinkContainer').show();
                } else {
                    $('#HcpAccountLinkContainer').hide();
                }
            });

            @if(!empty($user))

            $('#HcpAccountLinkContainer').hide();

            @endif

            //After email is entered, copy it to the search box and search
            $('input[name=email]').change(function (e) { 
                let currentSearchVal = $.trim($('#HcpSearch').val());
                if(currentSearchVal == ''){
                    $('#HcpSearch').val($(this).val());
                    $('#HcpSearchSubmit').click();
                }
            });
            $('input[name=password]')
                .attr('disabled', 'disabled')
                .css('opacity', '0.4');
            $('#HcpSearchSubmit').click(function(e) {
                e.preventDefault();
                $('#HcpSearchResultsContainer')
                    .html('Searching...')
                    .load('/app/search-hcp?q=' + $('#HcpSearch').val()); 
                return false;
            });

            $('#HcpSearchResultsContainer').delegate('input[name=external_id]', 'click', function(e) {
                let external_id = $(this).val();
                let sourceInputId = '#ExternalName_' + external_id;
                $('#ExternalName').val($(sourceInputId).val());
                return true;
            });
        });
    </script>

@endsection

resources/views/app/admin.blade.php
@extends('layouts.app', ['header' => 'Admin Dashboard'])

@section('content')

     
    <x-utilitymenu :items="[
        (object) ['text' => 'New User Account', 'url' => route('app.addaccount'), 'icon' => 'plus-circle'] 
    ]" />

    <div class="flex flex-col md:flex-row gap-4">
        <div class="md:w-8/12 text-xs md:text-sm">
            <x-subheading text="Request Tickets" />

            <div id="TicketsContainer" class="m-2 text-xs">
                
                <table class="w-full">
                    <!-- <thead>
                        <tr>
                            <th class="text-left">Customer</th>
                            <th class="text-left">Opened</th>
                            <th class="text-left">Last Updated</th>
                            <th class="text-left">Status</th>
                        </tr>
                    </thead>-->
                    <tbody>
                @foreach ($requestTickets as $requestTicket)
                    @php
                        $descr = $requestTicket->description;
                        if(strlen($descr) > 90) {
                            $descr = substr($descr, 0, 90) . '...';
                        }
                    @endphp
                        <tr class="">
                            <td class="text-left p-1 pb-0">
                                <span class="text-gray-400 block">Customer</span>
                                <strong>{{ $requestTicket->external_name }}</strong>
                            </td>
                            <td class="text-left p-1 pb-0"><span class="text-gray-400 block">Opened:</span> 
                                {{ $requestTicket->created_at->format('m/d/Y') }}</td>
                            <td class="text-left p-1 pb-0">
                                <span class="text-gray-400 block">Last Updated:</span> 
                                {{ $requestTicket->updated_at->diffForHumans() }}</td>
                            <td class="text-left p-1 pb-0">
                                <span class="text-gray-400 block">Status:</span> 
                                {{ $requestTicket->status }}</td>
                        </tr>
                        <tr class="mb-4 pb-4 border-gray-200 border-b">
                            <td colspan="4" class="p-1 pb-2 text-gray-700">
                                <a href="/tickets/view/{{ $requestTicket->id }}" class="page-link">{{ $descr }}</a>
                            </td>
                        </tr>
                @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="md:w-4/12 text-xs md:text-xs" style="font-size: x-small;">
            <x-subheading text="Users" />
            
            <div class="max-h-96 overflow-y-auto">
            
            @foreach ($users as $user)
                

                <div class="bg-gray-50 mb-2 p-1 pl-2 rounded-md">
                    <div class="flex flex-row gap-2">
                        <div class="w-7/12">
                            <span style="font-size: smaller;" class="text-gray-300"><x-icon type="user" /></span>
                            <a href="/app/user/{{ $user->id }}" class="page-link">
                                {{ $user->name }}
                            </a>
                        </div>
                        <div class="w-5/12">
                            {{ $user->account_type }}
                        </div>
                        
                    </div>
                    <div class="clear-both"></div>
                    <div class="flex flex-row gap-2">
                        
                        <div class="w-7/12 truncate elipsis">
                            <a class="page-link" href="mailto:{{ $user->email }}">{{ $user->email }}</a>
                        </div>
                        <div class="w-5/12 truncate elipsis">
                            {{ $user->external_name }}
                        </div>
                    </div>
                </div>

            @endforeach
            
            </div>
            
        </div>
    </div>
     
    


@endsection

resources/views/app/completeRegistration.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>TeoPros Portal - Complete User Registration</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="http://localhost/css/app.css">

        <!-- Scripts -->
        <script src="http://localhost/js/app.js" defer></script>
        <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous">
        </script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
    <div>
        <a href="/">
                <img src="/images/app-logo.png" id="AppLogo">            </a>
    </div>

    <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
        <!-- Session Status -->
        
        <!-- Validation Errors -->
        <h3 class="text-center mb-4">Complete your registration by creating a new password.</h3>
        {{  Form::open(['url' => '/complete-registration/'.$emailToken.'?key='.$key]) }}

            <input type="password" name="password" placeholder="Password" class="w-full border-0 bg-gray-100 rounded-lg" />
            <hr class="my-5">
            <input type="password" name="password_confirmation" placeholder="Confirm Password" class="w-full border-0 bg-gray-100 rounded-lg" />
            <div class="text-center">
                <x-submitbutton text="Complete Registration" />
            </div>
        {{ Form::close() }}

    </div>
</div>
        </div>

        <script>
            $(document).ready(function() {
                $('input[name=submit]').click(function(e) {
                    let val1 = $('input[name=password]').val();
                    let val2 = $('input[name=password_confirmation]').val();
                    if(val1 != val2) {
                        e.preventDefault();
                        alert('Passwords do not match');
                        return false;
                    }
                    return true;
                });
            });
        </script>
    </body>
</html>

resources/views/app/deregistered.blade.php
@extends('layouts.app', ['header' => 'Account Inactive'])

@section('content')
    <h3>
        Your account is currently inactive. Please contact the administrator for more information.
    </h3>
    
@endsection

resources/views/app/search.blade.php
@extends('layouts.app', ['header' => 'Search Results'])

@section('content')

    <h3 class="text-xl mb-5">Search Results for: &quot;{{ $searchTerm }}&quot;</h3>

    <div class="flex flex-row gap-4">
        <div class="w-full md:3/6">
            <x-subheading text="Request Tickets" />

            @foreach ($requestTickets as $requestTicket)
            
                <div class="ticket-search-result m-2 bg-gray-50 py-1 px-3">
                    <span class="text-gray-300"><x-icon type="ticket" /></span>
                    <a href="/tickets/view/{{ $requestTicket->id }}" class="page-link text-lg">Ticket# {{ $requestTicket->id }}</a><br>
                    <small>{{ nl2br(substr($requestTicket->description, 0, 75)) }}...</small>
                </div>

            @endforeach

        </div>
        <div class="w-full md:3/6">
            <x-subheading text="Users" />

            @foreach ($users as $user)
            
                <div class="user-search-result m-2 bg-gray-50 p-1 px-3">
                    <span class="text-gray-300"><x-icon type="user" /></span>
                    <a class="page-link" href="/app/user/{{ $user->id }}">{{ $user->name }}</a><br>
                    <small>{{ $user->email }}</small>
                </div>

            @endforeach

        </div>

    </div>  


@endsection

resources/views/app/searchhcp.blade.php
@extends('layouts.app', ['header' => 'HCP Search'])

@php 

    #
    # Local formatting functions 
    #

    function _customerName($customer)
    {
        if(empty($customer->first_name) and empty($customer->last_name))
        {
            return '(None)';
        }
        return $customer->first_name.' '.$customer->last_name;
    }

    function _customerCompany($customer)
    {
        if(empty($customer->company) )
        {
            return '(None)';
        }
        return $customer->company;
    }

    function _customerPhone($customer)
    {
        if(empty($customer->mobile_number) )
        {
            return '(None)';    
        }
        return '<a class="page-link" href="tel:'.$customer->mobile_number.'">'.$customer->mobile_number.'</a>';
    }

    function _customerLocation($customer)
    {
        if(empty($customer->addresses) )
        {
            return '';
        }
        return $customer->addresses[0]->city.', '.$customer->addresses[0]->state;
    }

    function _customerEmail($customer)
    {
        if(empty($customer->email))
        {
            return '(None)';
        }
        return '<a class="page-link" href="mailto:'.$customer->email.'">'.$customer->email.'</a>';
    }

@endphp

@section('content')

    <div class="m-2">
        <h4>Search Results for &quot;{{ $query }}&quot; </h4>
        
        @php
            $count = 0; 
        @endphp

        @foreach ($customers->customers as $customer)
            
            @php 
                $rowClass = ($count % 2 == 1) ? 'bg-white' : 'bg-gray-50';
                $count++;
            @endphp
            
            <label class="block flex text-xs gap-2 mb-2 {{ $rowClass }}">
                    <div class="flex-none w-1/12 truncate bg-blue-50 p-2 rounded-md text-center">
                        {{ Form::radio('external_id', $customer->id, false) }}
                        <input type="hidden" id="ExternalName_{{ $customer->id }}" value="{{ $customer->company }}" />
                    </div>
                    <div class="flex-1 w-3/12 text-ellipsis truncate p-2">
                        {!! _customerName($customer) !!}
                    </div>
                    <div class="flex-1 w-2/12 text-ellipsis truncate p-2">
                        {!! _customerCompany($customer) !!}
                    </div>
                    <div class="flex-1 w-2/12 text-ellipsis truncate p-2">
                        {!! _customerLocation($customer) !!}
                    </div>
                    <div class="flex-1 w-2/12 text-ellipsis truncate p-2">
                        {!! _customerEmail($customer) !!}
                    </div>
                    <div class="flex-1 w-2/12 text-ellipsis truncate p-2">
                        {!! _customerPhone($customer) !!}
                    </div>
            </label>
        @endforeach
    </div>

@endsection

resources/views/app/user.blade.php
@extends('layouts.app', ['header' => 'User Profile'])

@section('content')


<script>
    $(document).ready(function(){
        $('.utility-menu').find('a:contains(Add Note)').click(function(e){
                e.preventDefault();
                $('#AddUserNoteForm').slideDown();
                return false;
            });
            $('.form-closer span').click(function(e){
                e.preventDefault();
                $(this).parents('.user-note-form').slideUp();
                return false;
            }).css('cursor', 'pointer');

        $("a:contains('activate Account')").click(function(e){
            if(!confirm('Are you sure?')){
                e.preventDefault();
                return false;
            }
            return true;
        });
    });
</script>

@php
    $activateLabel = ($user->is_active) ? 'Deactivate Account' : 'Activate Account';
@endphp

<x-utilitymenu :items="[
        (object) ['text' => 'Update User', 'url' => route('app.edituser', $user->id), 'icon' => 'pencil-alt'] , 
        (object) ['text' => 'Add Note', 'url' => '/app/add-user-note/'.$user->id, 'icon' => 'chat-alt'], 
        (object) ['text' => $activateLabel, 'url' => '/app/toggle-user-activation/'.$user->id, 'icon' => 'minus-circle'], 
    ]" />

<div id="AddUserNoteForm" style="display: none;" class="mb-8 user-note-form">
    <x-subheading text="Add Note to User" />

    {{ Form::open(['url' => '/app/add-note']) }}
    
    <input type="hidden" name="object_type" value="User" hidden>
    <input type="hidden" name="object_id" value="{{ $user->id }}" hidden>
    <input type="hidden" name="redirect" value="back" hidden>

    <div class="flex flex-row">
        <div class="m-2 mb-0 w-11/12">
            <x-forminput :params="[
                'type' => 'textarea',
                'name' => 'note',
                'label' => 'Note'
            ]" /> 
        </div>
        <div class="w-1/12 pt-4 text-xl form-closer text-gray-400">
            <span><x-icon type="x-circle" fill="1" /></span>
        </div>
    </div>

    <x-submitbutton />
    
    {{ Form::close() }}
    
    <div class="m-6"></div>
</div>

<x-subheading text="Details" />
<div class="flex flex-col-reverse md:flex-row lg:flex-row gap-4 w-full">
    
    <div class="md:w-8/12 lg:w-6/12 -mt-5 md:mt-auto z-10 flex-1 ">
        <div class="border-t border-gray-200">
            @php
                $fields = [
                    'Name' => $user->name, 
                    'Account Type' => $user->account_type,
                    'Email' => $user->email,
                    'Since' => $user->created_at->diffForHumans() 
                ];

                if(!empty($user->external_id)){
                    $fields['HCP'] = $user->external_name;
                    $fields[''] = $user->external_id;
                }
                
            @endphp
            <dl>
                @foreach ($fields as $key => $value)
                    
                <div class="px-4 py-3 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 border-b bg-gray-50">
                    <dt class="text-sm font-medium text-gray-500">
                        {{ $key }}
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        {{ $value }}
                    </dd>
                </div>
        
                @endforeach

            </dl>
        </div>
    </div>
    <div class="md:w-2/12 lg:w-2/12 text-center z-20">
        <span class="inline-block p-3 bg-gray-50 rounded-full shadow text-center align-middle">
            <x-icon type="user" />
        </span>
    </div>
</div>

<div class="m-8"></div>

<x-subheading text="History" />

@include('partials.historicalNotes')

@endsection